# Generated by Django 3.2.6 on 2021-09-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_input', models.DateTimeField(auto_now_add=True)),
                ('link_name', models.CharField(max_length=250)),
                ('link_link', models.TextField()),
            ],
            options={
                'ordering': ['-date_input'],
            },
        ),
    ]
